alias dwvlacc='deploy "(WVL 2014) acc deploy"'
alias dwvldev='deploy "(WVL 2014) dev deploy"'
alias drkgemprod='deploy "(DRK7-GEMEENTEN-OMEGA) deploy update"'
alias drkgemstage='deploy "(DRK7-STAGING-GEMEENTES-OMEGA) deploy update"'
alias vjfacc='deploy "(VJF-acc) deploy"'
alias vjfdev='deploy "(VJF-dev) deploy"'
alias vjfprod='deploy "(VJF-prod) deploy"'
